name: Apply
on:
  issue_comment:
    types: [created]
    
jobs:
  # This workflow contains a single job called "apply". It only runs on the /ok-to-apply command
  tf-apply:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.html_url, '/pull/') && startsWith( github.event.comment.body, '/ok-to-apply' )
    steps:
      - id: get-ref
        name: Get branch name
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
            const response = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            });

            return response.data.head.ref;
      - uses: olivercodes/owners-slash-command@v1.0.11
        id: perm
        env:
          ORG_TOKEN: ${{ secrets.ORG_TOKEN }}
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        if: failure() && steps.perm.outcome == 'failure'
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - Created by [test][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.get-ref.outputs.result }}

